name: postman_dio
description: Logger Interceptor for Dio with export to "Postman Collection v2.1".json
version: 0.9.4
author: zfx.com
homepage: https://pub.dev/packages/postman_dio
repository: https://github.com/zfx-com/postman_dio/tree/master
issue_tracker: https://github.com/zfx-com/postman_dio/issues

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio:

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: 


