name: postman_dio
description: Logger Interceptor for Dio with export to "Postman Collection v2.1".json
version: 1.0.0
homepage: https://github.com/zfx-com
repository: https://github.com/zfx-com/postman_dio/tree/master
issue_tracker: https://github.com/zfx-com/postman_dio/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: '>=4.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: 


