name: postman_dio
description: Logger Interceptor for Dio with export to "Postman Collection v2.1".json
version: 0.9.0
author: zfx.com
homepage: https://pub.dev/packages/postman_dio

environment:
  sdk: ">=2.4.0 <3.0.0"

dependencies:
  dio:

dev_dependencies:
  flutter_test:
    sdk: flutter

