name: postman_dio
description: Logger Interceptor for Dio with export to "Postman Collection v2.1".json
version: 0.1.0-dev.5
homepage: https://github.com/febinfathah

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: 


